import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export async function generatePdf() {
  const input = document.getElementById("pdf-content");
  // Selects each A4 page div generated by your pagination logic
  const pages = input.querySelectorAll(".relative.bg-white");
  const pdf = new jsPDF("p", "mm", "a4");

  for (let i = 0; i < pages.length; i++) {
    // Hide the "Edit" buttons during PDF generation
    const editButtons = pages[i].querySelectorAll("button");
    editButtons.forEach(btn => btn.style.display = "none");

    const canvas = await html2canvas(pages[i], {
      scale: 2, // Increases quality for clear Hindi text
      useCORS: true, // Allows loading images from external URLs
      logging: false,
    });

    // Show the "Edit" buttons again after capturing
    editButtons.forEach(btn => btn.style.display = "block");

    const imgData = canvas.toDataURL("image/jpeg", 1.0);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();

    pdf.addImage(imgData, "JPEG", 0, 0, pdfWidth, pdfHeight);

    // If there is another page in the preview, add it to the PDF
    if (i < pages.length - 1) {
      pdf.addPage();
    }
  }

  pdf.save("One-Word-Substitution.pdf");
}